### ISSUE TITLE
version update

### ISSUE THREAD

**Issue by wolfy67** [iusrepo/phpMyAdmin49#1]
Hello. Could you please update the package to 4.9.3 ? And maybe also package the current version ( 5.0 ) ?
TIA

**Comment by carlwgeorge** [comment]
I just updated the spec file, I'll publish the updated RPMs to the testing repos once the build is complete.

If you'd like to request phpMyAdmin50, please open a request on our [wishlist](https://github.com/iusrepo/wishlist).

**Comment by petecassetta** [comment]
Thanks for the 4.9.3 update Carl; I will begin testing it.

I think that for Rackspace customers, phpMyAdmin 4.9 is preferable to 5.0 because 4.9 supports PHP 5.5, 5.6, and 7.0. phpMyAdmin 5.0 drops support for these versions. Since 4.9 is an LTS release, this should work well for us until PHP 5.x becomes less relevant for our customers.

Of course, there are advantages to phpMyAdmin 5.0, so others might request this version. But I don't think Rackspace sysadmins have a strong motivation to request it.
